language: python
python:
    - "3.8"
install: 
    - "pip install -r requirements.txt"
    - pip install coverage
script:
    - SECRET_KEY="placeholdersecretkey" python manage.py test
    - SECRET_KEY="placeholdersecretkey" coverage run --source=boutique_ado manage.py test
after_success:
    - coverage -t 8fe0b5c5-36e0-49d7-8ff8-6f7b7d4518c0
