language: python
python:
    - "3.8"
install: 
    - "pip3 install -r requirements.txt"
    - pip3 install coverage
script:
    - SECRET_KEY="placeholdersecretkey" python manage.py test
    - coverage run --source=boutique_ado manage.py test